### ISSUE TITLE
xo65 objects

### ISSUE THREAD

**Issue by polluks** [SvenMichaelKlose/tunix#2]
.gitignore contains *.o, but there are many object files in the repo.

**Comment by SvenMichaelKlose** [comment]
OK, thanks! I didn't want no sources zipped up, just the bunch of disk images. m( It's not release time at the moment. Just messing around with those workflow things should I ever get to understand 1541 I/O...

**Comment by SvenMichaelKlose** [comment]
Also added some extra cleaning. I hope you're satisfied. 8)
